name: chat_gpt_flutter_quan
description: A new Flutter project.

publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  get: ^4.6.5
  # flutter_chat_ui: ^1.6.6
  flutter_chat_ui:
    git:
      url: https://github.com/daominhquan1706/flutter_chat_ui.git
      ref: main

  google_fonts: ^4.0.3
  google_mobile_ads: ^2.3.0
  firebase_remote_config: ^3.0.15
  firebase_core: ^2.8.0
  markdown_widget: ^2.0.0+1
  dio: ^5.0.3
  flutter_client_sse: ^1.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_flavorizr: ^2.1.4
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

# terminal: flutter pub run flutter_flavorizr
flavorizr:
  app:
    android:
      flavorDimensions: "app"
    ios:

  flavors:
    prod:
      app:
        name: "Chatty GPT"

      android:
        applicationId: "com.quan.chatty"
        icon: "assets/images/logo.jpg"
        firebase:
          config: ".firebase/prod/google-services.json"

      ios:
        bundleId: "com.quan.chatty"
        icon: "assets/images/logo.jpg"
        # firebase:
        #   config: ".firebase/prod/GoogleService-Info.plist"
