// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX21sCxn3wNNryVRPi0lFnZ731m9W883E',
    appId: '1:207692103631:web:60e56d1fe04ae589155cba',
    messagingSenderId: '207692103631',
    projectId: 'chattygpt-b93c7',
    authDomain: 'chattygpt-b93c7.firebaseapp.com',
    storageBucket: 'chattygpt-b93c7.appspot.com',
    measurementId: 'G-KQ9RNMQK88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCythzPAII101IEzf6JbbIYpihdnu2ZqVQ',
    appId: '1:207692103631:android:f90c2257c99a3756155cba',
    messagingSenderId: '207692103631',
    projectId: 'chattygpt-b93c7',
    storageBucket: 'chattygpt-b93c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9yG61ogKiIA8eblEKw2SvY5lPHzO_JM8',
    appId: '1:207692103631:ios:621a8d703d2b34f4155cba',
    messagingSenderId: '207692103631',
    projectId: 'chattygpt-b93c7',
    storageBucket: 'chattygpt-b93c7.appspot.com',
    iosClientId: '207692103631-v5ok0629pkrtjkc87qqb16885uakqb9m.apps.googleusercontent.com',
    iosBundleId: 'com.quan.chatty',
  );
}
